Hw spring tests
mate-academy/spring-tests pull request #106
Opened 2023-03-05 12:33 UTC by DanyloBorysenko

2023-03-05 19:36 UTC, olekskov requested changes

2023-03-05 19:36 UTC, olekskov commented on src/test/java/mate/academy/dao/RoleDaoTest.java
> +        session.close();
Please use related dao methods in both dao tests classes.
I understand that you wanted to isolate get methods from effect of possible failure on save. But unit tests should be as simple as possible. If we have problems with save in test that designed for checking get logic then we will see it during debug in a minute and proceed with bugfixing in code. But if we will get fail on some big logic hardcoded within test then we will need to spend much more additional time to understand the cause of a problem

2023-03-05 19:36 UTC, olekskov commented on src/test/java/mate/academy/security/AuthenticationServiceTest.java
> +        }
Please rework all try/catches with assertThrows methods:
```suggestion
        AuthenticationException ex = assertThrows(AuthenticationException.class,
                () -> authenticationService.register(null, password));
        assertEquals("Email and password can't be null", ex.getMessage());
```

2023-03-05 19:36 UTC, olekskov commented on src/main/java/mate/academy/security/AuthenticationServiceImpl.java
> +            throw new RuntimeException("Email and password can't be null");
Please use AuthenticationException

2023-03-05 19:36 UTC, olekskov commented on src/test/java/mate/academy/security/jwt/JwtTokenProviderTest.java
> +        roles = List.of("ADMIN");
I cannot see any change of these variable in tests, why to set it before each one?

2023-03-07 11:22 UTC, kozhukhovsky approved these changes

2025-09-15 12:52 UTC, closed without merging